{% set name = "pymeeus" %}
{% set version = "0.5.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMeeus-{{ version }}.tar.gz
  sha256: bb9d670818d8b0594317b48a7dadea02a0594e5344263bf2054e1a011c8fed55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pymeeus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/architest/pymeeus
  summary: Python implementation of Jean Meeus astronomical routines
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ocefpaf
