{% set name = "pymeeus" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMeeus-{{ version }}.tar.gz
  sha256: 6b64d401d68e82a62dc57b94c9e88f730f5d6d8e8c44d2e896c7e772b14527a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pymeeus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/architest/pymeeus
  summary: Python implementation of Jean Meeus astronomical routines
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ocefpaf
