{% set name = "pymeeus" %}
{% set version = "0.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyMeeus-{{ version }}.tar.gz
  sha256: 116937baaa45897929ad3f1bd3f6dd4cb407c22bf06b194b700bcc7d3159f1d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pymeeus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/architest/pymeeus
  summary: Python implementation of Jean Meeus astronomical routines
  license: LGPL-3.0
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ocefpaf
