{% set name = "PyMeeus" %}
{% set version = "0.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 548f7186bd8b96cbc069cf649a8e8e377dce49ac74486709849fe63a99cad684

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pymeeus
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    # https://github.com/architest/pymeeus/issues/24
    - pytest <=7.2

about:
  home: https://github.com/architest/pymeeus
  summary: Python implementation of Jean Meeus astronomical routines
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  description: |
    PyMeeus is a Python implementation of the astronomical algorithms described in the
    classical book 'Astronomical Algorithms, 2nd Edition, Willmann-Bell Inc. (1998)' by Jean Meeus.
  dev_url: https://github.com/architest/pymeeus
  doc_url: https://pymeeus.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
