{% set version = "0.3.8" %}


package:
  name: pymeeus
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyMeeus/PyMeeus-{{ version }}.tar.gz
  sha256: ef398fb9b690d949dbd25827174ef111ece4988cb7cc3b3b3d682072cf9d4344

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pymeeus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/PyMeeus/
  summary: Python implementation of Jean Meeus astronomical routines
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ocefpaf
